name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: readline
      run: 'sudo apt install libreadline-dev'
    - name: cd core
      run: "cd core && mkdir build"
    - name: cd build
      run: "cd core/build && cmake .."
    - name: cmake --build
      run: "cd core && cmake --build build"
